// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN_SnURiGgcwfTy7VHtrJPxfFk93j8bH8',
    appId: '1:831873499989:web:ae8cc7b533673c9bc4e5dc',
    messagingSenderId: '831873499989',
    projectId: 'flutter-task-mngr-fb',
    authDomain: 'flutter-task-mngr-fb.firebaseapp.com',
    storageBucket: 'flutter-task-mngr-fb.firebasestorage.app',
    measurementId: 'G-2P0109M6L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAS5XIyaEtXTCW0Ksxl4VweO5Sxg642UA',
    appId: '1:831873499989:android:0d5b9f377cba36b9c4e5dc',
    messagingSenderId: '831873499989',
    projectId: 'flutter-task-mngr-fb',
    storageBucket: 'flutter-task-mngr-fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVcerVinqUhY6eJdWd8TEtqIxAvxL3xMo',
    appId: '1:831873499989:ios:4c11e363ea20dcbdc4e5dc',
    messagingSenderId: '831873499989',
    projectId: 'flutter-task-mngr-fb',
    storageBucket: 'flutter-task-mngr-fb.firebasestorage.app',
    iosBundleId: 'com.example.interviewTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVcerVinqUhY6eJdWd8TEtqIxAvxL3xMo',
    appId: '1:831873499989:ios:4c11e363ea20dcbdc4e5dc',
    messagingSenderId: '831873499989',
    projectId: 'flutter-task-mngr-fb',
    storageBucket: 'flutter-task-mngr-fb.firebasestorage.app',
    iosBundleId: 'com.example.interviewTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN_SnURiGgcwfTy7VHtrJPxfFk93j8bH8',
    appId: '1:831873499989:web:6d6cdc028a281a07c4e5dc',
    messagingSenderId: '831873499989',
    projectId: 'flutter-task-mngr-fb',
    authDomain: 'flutter-task-mngr-fb.firebaseapp.com',
    storageBucket: 'flutter-task-mngr-fb.firebasestorage.app',
    measurementId: 'G-RWFYP6W7L1',
  );
}
